# Generated by Django 3.2.16 on 2023-04-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteryroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 17, 51, 18, 456756)),
        ),
    ]
