# Generated by Django 3.2.16 on 2023-04-17 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteryroom', '0002_alter_timer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 11, 43, 3, 778072)),
        ),
    ]
