# Generated by Django 3.2.16 on 2023-04-11 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysteryroom', '0002_mysteryroom_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryroom',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mysteryroom',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 14, 10, 34, 68309))),
                ('penalty', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField(null=True)),
                ('latest_question', models.IntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysteryroom.mysteryroom')),
            ],
        ),
    ]
