# Generated by Django 3.2.16 on 2023-04-11 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteryroom', '0003_auto_20230411_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='user_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 15, 50, 53, 845973)),
        ),
    ]
