# Generated by Django 3.2.16 on 2023-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysteryroom', '0003_alter_timer_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysteryroom',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='mysteryroomcollection',
            name='number_of_team_members',
        ),
        migrations.RemoveField(
            model_name='mysteryroomquestion',
            name='total_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
