# Generated by Django 4.1.5 on 2023-01-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=20)),
                ('bg_image', models.TextField()),
                ('number_of_questions', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscapeRoomQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('number_of_images', models.IntegerField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('question_type', models.IntegerField()),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answers', models.TextField()),
                ('hints', models.TextField(null=True)),
                ('escape_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.escaperoomdetails')),
            ],
        ),
    ]
