# Generated by Django 4.1.5 on 2023-01-18 08:51

from django.db import migrations, models
import django.db.models.deletion
import escaperoom.utils


class Migration(migrations.Migration):

    dependencies = [
        ('escaperoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=20)),
                ('bg_image', models.TextField()),
                ('number_of_questions', models.IntegerField()),
                ('level', models.IntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')], default=escaperoom.utils.LevelTypes['EASY'])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('number_of_images', models.IntegerField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('question_type', models.IntegerField(choices=[(1, 'TEXTBOX'), (2, 'MCQ')], default=escaperoom.utils.QuestionChoices['TEXTBOX'])),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('answers', models.TextField()),
                ('hints', models.TextField(null=True)),
                ('escape_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.detail')),
            ],
        ),
        migrations.RemoveField(
            model_name='escaperoomquestions',
            name='escape_room',
        ),
        migrations.DeleteModel(
            name='EscapeRoomDetails',
        ),
        migrations.DeleteModel(
            name='EscapeRoomQuestions',
        ),
    ]
