# Generated by Django 4.1.5 on 2023-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaperoom', '0002_detail_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
