# Generated by Django 4.1.5 on 2023-01-23 04:46

from django.db import migrations, models
import django.db.models.deletion
import escaperoom.utils


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_escaperoomquestions_escape_room_and_more'),
        ('escaperoom', '0003_detail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.event'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_images',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(blank=True, choices=[(1, 'TEXTBOX'), (2, 'MCQ')], default=escaperoom.utils.QuestionChoices['TEXTBOX'], null=True),
        ),
    ]
