# Generated by Django 4.1.5 on 2023-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaperoom', '0004_detail_event_alter_question_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
