# Generated by Django 4.1.5 on 2023-01-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_escaperoomquestions_escape_room_and_more'),
        ('escaperoom', '0005_alter_detail_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.event')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.team')),
            ],
        ),
    ]
