# Generated by Django 4.1.3 on 2023-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_player_activity_team_current_size_team_team_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='activity',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
