# Generated by Django 4.1.4 on 2023-01-12 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_player_activity_team_current_size_team_team_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(null=True, upload_to='activity_plank/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
