# Generated by Django 4.1.3 on 2023-01-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_player_activity_alter_team_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
