# Generated by Django 4.1.3 on 2023-01-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_activity_activity_logo_alter_team_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_mode', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_teams', models.IntegerField(default=5)),
                ('max_members', models.IntegerField(default=5)),
                ('first_prize', models.IntegerField(default=100)),
                ('second_prize', models.IntegerField(default=75)),
                ('third_prize', models.IntegerField(default=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.activity')),
            ],
        ),
    ]
