# Generated by Django 4.1.3 on 2023-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cur_participation',
            field=models.IntegerField(default=0),
        ),
    ]
