# Generated by Django 4.1.3 on 2023-01-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230117_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
    ]
