# Generated by Django 4.1.4 on 2023-01-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_escaperoomquestions_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaperoomquestions',
            name='escape_room',
        ),
        migrations.DeleteModel(
            name='EscapeRoomDetails',
        ),
        migrations.DeleteModel(
            name='EscapeRoomQuestions',
        ),
    ]
