# Generated by Django 4.1.3 on 2023-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_player_score_player_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='activity_id',
            field=models.IntegerField(default=0),
        ),
    ]
