# Generated by Django 4.1.4 on 2023-01-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_player_activity_activity_activity_logo_and_more'),
        ('app1', '0012_alter_escaperoomquestions_images_and_more'),
    ]

    operations = [
    ]
