# Generated by Django 4.1.3 on 2023-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
