# Generated by Django 4.1.3 on 2023-01-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_event_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity_mode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_on',
        ),
    ]
