# Generated by Django 4.1.3 on 2023-01-23 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_event_activity_mode_remove_event_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_mode',
            field=models.TextField(default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 13, 39, 54, 516434)),
        ),
    ]
