# Generated by Django 4.1.3 on 2023-01-23 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_event_activity_mode_event_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 13, 52, 54, 899220)),
        ),
    ]
