# Generated by Django 4.1.5 on 2023-02-01 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_event_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 19, 1, 39, 193421)),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
