# Generated by Django 4.1.4 on 2023-02-02 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_event_created_on_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 13, 53, 37, 869206)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
