# Generated by Django 4.1.5 on 2023-02-16 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_event_created_on_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 15, 26, 57, 461143)),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
