# Generated by Django 4.1.4 on 2023-02-02 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_event_created_on_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='profilePic',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='detail',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 9, 18, 30903)),
        ),
    ]
