# Generated by Django 3.2.16 on 2023-02-02 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_rename_profilepic_detail_profile_pic_detail_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 17, 23, 40, 57780)),
        ),
    ]
