# Generated by Django 4.1.4 on 2023-02-08 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_event_created_on_alter_event_name_pod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='pod_members',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 13, 45, 46, 780176)),
        ),
    ]
