# Generated by Django 4.1.3 on 2023-02-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_event_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_teams',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.TextField(default='Group', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='min_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_members',
            field=models.IntegerField(default=0),
        ),
    ]
