# Generated by Django 4.1.3 on 2023-02-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_indregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
