# Generated by Django 4.1.3 on 2023-02-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_rename_pod_members_pod_user_alter_event_created_on'),
        ('app1', '0037_alter_team_name'),
    ]

    operations = [
    ]
