# Generated by Django 4.1.4 on 2023-02-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0039_alter_event_created_on_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.event'),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
