# Generated by Django 4.1.4 on 2023-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_upload_file_duration_upload_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_frame',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
