# Generated by Django 4.1.4 on 2023-02-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_upload_file_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file_frame',
        ),
    ]
