# Generated by Django 4.1.4 on 2023-02-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_upload_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_duration',
            field=models.TextField(blank=True, null=True),
        )#,
        # migrations.AlterField(
        #     model_name='upload',
        #     name='file_duration',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
