# Generated by Django 4.1.4 on 2023-02-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_alter_event_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
