# Generated by Django 4.1.4 on 2023-02-15 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0048_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('uploaded_file', models.FileField(null=True, upload_to='activity_plank/')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('file_duration', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('event', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.event')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
