# Generated by Django 4.1.3 on 2023-02-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='first_prize',
        ),
        migrations.RemoveField(
            model_name='event',
            name='second_prize',
        ),
        migrations.RemoveField(
            model_name='event',
            name='third_prize',
        ),
    ]
