# Generated by Django 4.1.4 on 2023-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_event_created_on'),
        ('app1', '0050_remove_event_first_prize_remove_event_second_prize_and_more'),
    ]

    operations = [
    ]
