# Generated by Django 4.1.4 on 2023-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_quiz_quizquestion_event_task_id_useranswer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Checkbox', 'Checkbox')], default='MCQ', max_length=20),
        ),
    ]
