# Generated by Django 3.2.16 on 2023-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='for_user',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
