# Generated by Django 3.2.16 on 2023-03-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_option_quiz_quizquestion_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.quiz'),
            preserve_default=False,
        ),
    ]
