# Generated by Django 4.1.4 on 2023-03-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_quiz_quizquestion_useranswer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='event',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.event'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct_answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
