# Generated by Django 3.2.16 on 2023-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_option_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
