# Generated by Django 4.1.4 on 2023-03-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_quiz_event_alter_useranswer_is_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.quiz'),
        ),
    ]
