# Generated by Django 3.2.16 on 2023-03-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_quizquestion_question_type'),
        ('app1', '0055_alter_notifications_options'),
    ]

    operations = [
    ]
