# Generated by Django 3.2.16 on 2023-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_merge_20230322_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploaded_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
