# Generated by Django 4.1.4 on 2023-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_quiz_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='submitted_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
