# Generated by Django 3.2.16 on 2023-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_auto_20230322_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
