# Generated by Django 4.1.4 on 2023-03-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_quiz_quizquestion_event_task_id_useranswer_option'),
        ('app1', '0058_alter_useranswer_submitted_answer'),
    ]

    operations = [
    ]
